baseURL = 'https://blog.251819788.xyz/'
languageCode = 'zh-cn'
title = '个人博客'
theme = 'PaperMod'

[params]
  author = '张二浩'
  # 主题相关配置
  env = 'production'
  description = '欢迎来到我的个人博客'
  keywords = ['博客', '科技', '信息', 'AI']
  # 开启导航栏
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true

# 配置菜单
[[menu.main]]
  identifier = 'home'
  name = '首页'
  url = '/'
  weight = 1

[[menu.main]]
  identifier = 'posts'
  name = '文章'
  url = '/posts/'
  weight = 2

[[menu.main]]
  identifier = 'about'
  name = '关于'
  url = '/about/'
  weight = 3
